<?php

namespace Ebookblog\BlogBundle\Repository;

/**
 * LegalMentionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalMentionsRepository extends \Doctrine\ORM\EntityRepository
{
}
