ebook_blog_homepage:
    path:     /
    defaults: { _controller: EbookBlogBundle:Front:index }

ebook_blog_view:
    path:     /chapter/{id}
    defaults:
        _controller: EbookBlogBundle:Front:view
    requirements:
        id: \d+

ebook_blog_login:
    path:     /login
    defaults: { _controller: EbookBlogBundle:Front:login }

ebook_blog_adminpage:
    path:     /admin
    defaults: { _controller: EbookBlogBundle:Admin:index }

ebook_blog_chapters:
    path:     /admin/chapters
    defaults: { _controller: EbookBlogBundle:Admin:viewChapters}

ebook_blog_chapters_published:
    path:     /admin/published-chapters
    defaults: { _controller: EbookBlogBundle:Admin:viewPublishedChapters}

ebook_blog_chapters_unpublished:
    path:     /admin/unpublished-chapters
    defaults: { _controller: EbookBlogBundle:Admin:viewUnpublishedChapters}

ebook_blog_chapter_add:
    path:     /admin/chapter/add
    defaults: { _controller: EbookBlogBundle:Admin:addChapter }

ebook_blog_chapter_edit:
    path:     /admin/chapter/{id}/edit
    defaults:
        _controller: EbookBlogBundle:Admin:editChapter
    requirements:
        id: \d+

ebook_blog_chapter_delete:
    path:     /admin/chapter/{id}/delete
    defaults:
        _controller: EbookBlogBundle:Admin:deleteChapter
    requirements:
        id: \d+

ebook_blog_comments:
    path:     /admin/comments
    defaults: { _controller: EbookBlogBundle:Admin:viewComments }

ebook_blog_comments_unpublished:
    path:     /admin/unpublished-comments
    defaults: { _controller: EbookBlogBundle:Admin:viewUnpublishedComments }

ebook_blog_comment_accept:
    path:     /admin/comment/{id}/accept
    defaults:
        _controller: EbookBlogBundle:Admin:acceptComment
    requirements:
        id: \d+

ebook_blog_comment_delete:
    path:     /admin/comment/{id}/delete
    defaults:
        _controller: EbookBlogBundle:Admin:deleteComment
    requirements:
        id: \d+

