services:
#    ebook_blog.example:
#        class: Ebookblog\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    ebook_blog.twig_extension:
        class: Ebookblog\BlogBundle\Twig\ChaptersMenu
        arguments:
            doctrine: "@doctrine"
            twig:  "@twig"
        public: false
        tags:
            - {name: twig.extension}
