# app/config/security.yml

security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    Ebookblog\BlogBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      entity:
        class: Ebookblog\BlogBundle\Entity\User
        property: username


  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
        pattern:    ^/
        anonymous: true
        provider: main
        form_login:
            login_path: ebook_blog_login
            check_path: login_check
        logout:
            path:    logout
            target:  /

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
